// Mock AI functions for demo

export const generateEmail = (options: {
  tone: string;
  purpose: string;
  keyPoints: string;
  subject: string;
}): string => {
  const tones = {
    professional: 'Dear [Recipient],\n\nI hope this message finds you well.',
    casual: 'Hey [Name],\n\nHope you\'re doing great!',
    persuasive: 'Hello [Recipient],\n\nI have an exciting opportunity to share with you.',
    friendly: 'Hi [Name],\n\nIt was great connecting with you!',
    formal: 'To Whom It May Concern,\n\nI am writing to formally address...'
  };

  const purposes = {
    'business': 'Regarding our business collaboration',
    'job-application': 'Job Application for [Position]',
    'follow-up': 'Following up on our previous conversation',
    'thank-you': 'Thank you for your assistance',
    'announcement': 'Important Announcement'
  };

  const toneText = tones[options.tone as keyof typeof tones] || tones.professional;
  const purposeText = purposes[options.purpose as keyof typeof purposes] || '';
  
  const currentDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return `Subject: ${options.subject || 'Important Message'}

${toneText}

${purposeText ? purposeText + ':\n\n' : ''}${options.keyPoints.split('\n').map(point => `• ${point}`).join('\n')}

${getClosingForTone(options.tone)}

[Your Name]
[Your Position]
[Your Contact Information]

---
Generated by AI Assistant on ${currentDate}`;
};

export const summarizePDF = async (filename: string, length: string = 'medium'): Promise<string> => {
  await new Promise(resolve => setTimeout(resolve, 1000));
  
  const lengths = {
    short: `Brief summary of "${filename}":\n\nThis document discusses key concepts in the field. Main points include important developments and future directions.`,
    medium: `Summary of "${filename}":\n\nThis comprehensive document explores various aspects of the subject matter. Key sections include:\n\n1. Introduction and background context\n2. Core concepts and methodologies\n3. Case studies and examples\n4. Analysis and findings\n5. Conclusions and recommendations\n\nThe material is well-structured and provides valuable insights.`,
    detailed: `Detailed Analysis of "${filename}":\n\nOVERVIEW:\nThis document presents an in-depth examination of the topic, spanning multiple chapters and sections.\n\nKEY SECTIONS:\n1. Historical Context - Traces the evolution of concepts\n2. Theoretical Framework - Establishes foundational principles\nn3. Methodological Approach - Details research methods used\n4. Empirical Findings - Presents data and analysis\n5. Discussion - Interprets results in broader context\n6. Implications - Discusses practical applications\n7. Future Directions - Suggests areas for further research\n\nMAIN ARGUMENTS:\n• Primary thesis supported by evidence\n• Counterarguments addressed\n• Synthesis of multiple perspectives\n\nCRITICAL INSIGHTS:\n• Key takeaways for practitioners\n• Theoretical contributions\n• Limitations and scope\n\nCONCLUSION:\nThe document makes significant contributions to the field and offers actionable recommendations.`
  };

  return lengths[length as keyof typeof lengths] || lengths.medium;
};

export const convertCode = (code: string, from: string, to: string): string => {
  const examples: Record<string, string> = {
    'python': `# Python example
def calculate_sum(numbers):
    return sum(numbers)

result = calculate_sum([1, 2, 3, 4, 5])
print(f"Sum: {result}")`,
    
    'javascript': `// JavaScript equivalent
function calculateSum(numbers) {
    return numbers.reduce((a, b) => a + b, 0);
}

const result = calculateSum([1, 2, 3, 4, 5]);
console.log(\`Sum: \${result}\`);`,
    
    'java': `// Java equivalent
import java.util.Arrays;

public class Calculator {
    public static int calculateSum(int[] numbers) {
        return Arrays.stream(numbers).sum();
    }
    
    public static void main(String[] args) {
        int[] numbers = {1, 2, 3, 4, 5};
        int result = calculateSum(numbers);
        System.out.println("Sum: " + result);
    }
}`,
    
    'cpp': `// C++ equivalent
#include <iostream>
#include <vector>
#include <numeric>

int calculateSum(const std::vector<int>& numbers) {
    return std::accumulate(numbers.begin(), numbers.end(), 0);
}

int main() {
    std::vector<int> numbers = {1, 2, 3, 4, 5};
    int result = calculateSum(numbers);
    std::cout << "Sum: " << result << std::endl;
    return 0;
}`
  };

  return `Converted from ${from.toUpperCase()} to ${to.toUpperCase()}:\n\n${examples[to] || 'Conversion not available'}`;
};

export const translateText = (text: string, fromLang: string, toLang: string): string => {
const translations: Record<string, Record<string, string>> = {
  'hello': {
    spanish: 'Hola',
    french: 'Bonjour',
    german: 'Hallo',
    urdu: 'ہیلو',
    arabic: 'مرحبا'
  },
  'thank you': {
    spanish: 'Gracias',
    french: 'Merci',
    german: 'Danke',
    urdu: 'شکریہ',
    arabic: 'شكرا'
  },
  'how are you': {
    spanish: '¿Cómo estás?',
    french: 'Comment allez-vous?',
    german: 'Wie geht es dir?',
    urdu: 'آپ کیسے ہیں؟',
    arabic: 'كيف حالك؟'
  }
};


  const lowerText = text.toLowerCase();
  const translation = translations[lowerText]?.[toLang] || 
                     `[${toLang.toUpperCase()}: Translation for "${text}"]`;

  return `${text}\n↓\n${translation}\n\nPronunciation: ${getPronunciation(toLang, translation)}`;
};

// Helper functions
function getClosingForTone(tone: string): string {
  const closings = {
    professional: 'Best regards,',
    casual: 'Cheers,',
    persuasive: 'Looking forward to your response,',
    friendly: 'All the best,',
    formal: 'Respectfully,'
  };
  return closings[tone as keyof typeof closings] || 'Sincerely,';
}

function getPronunciation(lang: string, text: string): string {
  const pronunciations: Record<string, string> = {
    spanish: `Pronounced: ${text}`,
    french: `Pronounced: ${text}`,
    german: `Pronounced: ${text}`,
    urdu: 'Right-to-left script',
    arabic: 'Right-to-left script'
  };
  return pronunciations[lang] || text;
}

// Add to src/utils/mockAI.ts

export const generateImage = (prompt: string, style: string, aspect: string): Promise<string> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const seed = Math.random().toString(36).substr(2, 9);
      const dimensions = aspect === '1:1' ? '800/800' :
                       aspect === '16:9' ? '1200/675' :
                       aspect === '9:16' ? '675/1200' :
                       aspect === '4:3' ? '1200/900' : '800/533';
      resolve(`https://picsum.photos/seed/${seed}/${dimensions}`);
    }, 2000);
  });
};


